format = """
[░▒▓](#7dcfff)\
[ 󰣇 ](fg:#1a1b26 bg:#7dcfff)\
[](fg:#7dcfff bg:#7aa2f7)\
$directory\
[](fg:#7aa2f7 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
\n$character"""

[directory]
style = "fg:#1a1b26 bg:#7aa2f7"
format = "[ $path ]($style)"
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'


[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
