return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'cpp',
      'css',
      'dart',
      'diff',
      'dockerfile',
      'go',
      'graphql',
      'html',
      'ini',
      'java',
      'javascript',
      'jsdoc',
      'json',
      'markdown',
      'markdown_inline',
      'php',
      'phpdoc',
      'python',
      'rasi',
      'regex',
      'robots',
      'ruby',
      'rust',
      'scss',
      'sql',
      'svelte',
      'toml',
      'twig',
      'typescript',
      'vim',
      'vimdoc',
      'vue',
      'xml',
      'yaml',
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = {
        'ruby',
      },
    },
    indent = {
      enable = true,
      disable = {
        'ruby',
      },
    },
  },
}
